server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.39.25.221:8761/eureka

spring:
  application:
    name: api-gateway
    cloud:
      - id: parabole
        uri: lb://PARABOLE
        predicates:
          - Path=/api/v1/**
      - id: the-parabole-event
        uri: lb://THE-PARABOLE-EVENT
        predicates:
          - Path=/api/v2/event/**
